### ISSUE TITLE
When a non-thread post gets author changed the threadcount is still changed 

### ISSUE THREAD

**Issue by TDSrock** [Sama34/OUGC-Admin-Post-Edit#1]
This one should be a relatively simple change.

This should resolve the issue

				if(isset($update))
				{
					global $plugins;

					$forum = get_forum($dh->data['fid']);
					$thread = get_thread($dh->data['tid']);

					$user = get_user($dh->post_update_data['uid']);

					$update_query = array();
					if($thread['dateline'] > $user['lastpost'])
					{
						$update_query['lastpost'] = "'{$thread['dateline']}'";
					}
					if($forum['usepostcounts'])
					{
						$update_query['postnum'] = 'postnum+1';
					}
					if($forum['usethreadcounts'])
					{
						if($thread['firstpost'] == $post['pid']){
							$update_query['threadnum'] = 'threadnum+1';
						} else {
							$update_query['threadnum'] = 'threadnum';
						}
					}

					if(!empty($update_query))
					{
						$db->update_query('users', $update_query, "uid='{$user['uid']}'", 1, true);
					}

					$user = get_user($dh->data['uid']);

					$update_query = array();
					if($thread['dateline'] < $user['lastpost'])
					{
						$update_query['lastpost'] = "'{$thread['dateline']}'";
					}
					if($forum['usepostcounts'])
					{
						$update_query['postnum'] = 'postnum-1';
					}
					if($forum['usethreadcounts'])
					{
						if($thread['firstpost'] == $post['pid']){
						        $update_query['threadnum'] = 'threadnum-1';
						} else {
							$update_query['threadnum'] = 'threadnum';
						}
					}

					if(!empty($update_query))
					{
						$db->update_query('users', $update_query, "uid='{$user['uid']}'", 1, true);
					}

					if($thread['firstpost'] == $post['pid'])
					{
						$thread_update = array(
							'uid'		=> $dh->post_update_data['uid'],
							'username'	=> $dh->post_update_data['username'],
							'dateline'	=> $dh->post_update_data['dateline']
						);

						$db->update_query('threads', $thread_update, "tid='{$thread['tid']}'");
					}

					$plugins->add_hook('datahandler_post_update_end', array($this, 'hook_datahandler_post_update_end'));
				}

**Comment by Sama34** [comment]
Thank you for your report.

I have pushed a fix in 24442309a2cbf5473d9e9f997b46645101f2f7fc if you could confirm it fixes the issue.
