### ISSUE TITLE
Inclusion of feature:  Non-Member Usernames

### ISSUE THREAD

**Issue by DerVVulfman** [Sama34/OUGC-Admin-Post-Edit#7]
Just upgraded from one version by MrBrechreiz to your newest version.  The 1.1 version used before allowed me to enter usernames for guest accounts, or make posts to credit original authors in order to archive content that was in danger of being lost.

**Describe the solution you'd like**
Please include a checkbox for 'Registered Members' as a default setting.

While checked, it would act as it does now, ignore if the name entered into the username field is not that of a registered user.

If unchecked, it would assume the name entered is not a registered member.  However, it would run a test against the member database to see if the name does exist. If it does, then a notification would appear that the name belongs to a registered member followed by  (Proceed/Cancel).

**Describe alternatives you've considered**
No alternatives really.   Everything else already covered in your latest, including the newer IP address style.

**Additional context**
I requested the earlier version in a forum found here:
http://mybbhacks.zingaburga.com/showthread.php?tid=5282
The second page includes an 'attachment' which is by 'MrBrechreiz', the version I had used.

**Comment by Sama34** [comment]
Hi, the next release will launch with this feature.
